kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
nodes:
- role: control-plane
  extraPortMappings:
  - containerPort: 80
    hostPort: 80
    protocol: TCP
  - containerPort: 443
    hostPort: 443
    protocol: TCP
  extraMounts:
  - hostPath: /tmp/logs/containers
    containerPath: /var/log/containers
  - hostPath: /tmp/logs/pods
    containerPath: /var/log/pods
  - hostPath: /tmp/logs/solr
    containerPath: /var/solr/logs
  - hostPath: /tmp/logs
    containerPath: /var/logs
kubeadmConfigPatches:
- |
    kind: InitConfiguration
    nodeRegistration:
      kubeletExtraArgs:
        node-labels: "ingress-ready=true"
        authorization-mode: "AlwaysAllow"
