apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-service
  name: my-service
spec:
  selector:
    app: my-deployment
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: ClusterIP
