apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: example-solrcloud-ingress
  namespace: solr
spec:
  defaultBackend:
    service:
      name: example-solrcloud-common
      port:
        number: 80
