apiVersion: v1
kind: Service
metadata:
  labels:
    app: this-is-service
  name: nginx-dep-svc
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: http
  selector:
    app: this-is-pod
