apiVersion: v1
kind: Secret
metadata:
  name: db-secret
type: Opaque
data:
  MYSQL_PASSWORD: cGFzc3dvcmQ=  # "password"をBase64エンコードしたもの
  MYSQL_ROOT_PASSWORD: cm9vdHBhc3N3b3Jk # "rootpassword"をBase64エンコードしたもの
