apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  replicas: 1
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.2
        env:
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret  # ここでSecretsを参照
              key: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret  # ここでSecretsを参照
              key: MYSQL_ROOT_PASSWORD
        envFrom:
        - configMapRef:
            name: db-config
        ports:
        - containerPort: 3306
