apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: bind-secret-reader
  namespace: default
subjects:
- kind: ServiceAccount
  name: my-app-sa  # ここでサービスアカウントを指定
  namespace: default
roleRef:
  kind: Role
  name: secret-reader  # 先ほど作成したRoleを指定
  apiGroup: rbac.authorization.k8s.io
