apiVersion: solr.apache.org/v1beta1
kind: SolrCloud
metadata:
  name: example
  namespace: solr
spec:
  customSolrKubeOptions:
    podOptions:
      resources:
        limits:
          cpu: 1
          memory: 1Gi
        requests:
          cpu: 700m
          memory: 500Mi
  dataStorage:
    persistent:
      pvcTemplate:
        spec:
          resources:
            requests:
              storage: 1Gi
      reclaimPolicy: Retain
  replicas: 3
  solrImage:
    repository: solr
    tag: "9.7"
  solrJavaMem: -Xms300m -Xmx300m
  solrOpts: "-Dsolr.configsetUploadMode=trusted"
  solrLogLevel: INFO
  updateStrategy:
    method: StatefulSet
  zookeeperRef:
    provided:
      chroot: /
      image:
        pullPolicy: IfNotPresent
        repository: pravega/zookeeper
      replicas: 1
      zookeeperPodPolicy:
        resources:
          limits:
            cpu: 250m
            memory: 250Mi
          requests:
            cpu: 100m
            memory: 100Mi
